client_config_backend: file
client_config_file: /opt/airflow/config/client_secrets.json
save_credentials: True
save_credentials_backend: file
save_credentials_file: /opt/airflow/config/mycreds.txt
get_refresh_token: True
